prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix xhtml: <http://www.w3.org/1999/xhtml#>
PREFIX xyz:  <http://sparql.xyz/facade-x/data/>
PREFIX fx:   <http://sparql.xyz/facade-x/ns/>

SELECT DISTINCT ?artistUrl ?artistNickname
WHERE {
    SERVICE <x-sparql-anything:media-type=text/html,html.selector=#	,location=https://imma.ie/artists/> {
        [] xhtml:data-image [] ;
			rdf:_1 [
			   xhtml:href ?artistUrl ;
			   ?i [ a xhtml:span ; rdf:_1 ?artistNickname2 ]
			].
    } .

	BIND( fx:String.trim(  ?artistNickname2 ) AS ?artistNickname ) .
}
